const rounds = [
    {
        answers: [
            {answer: "Partridge in a pear tree", fontSize: "1vw"},
            {answer: "Turtle Doves", fontSize: "1.5vw"},
            {answer: "French Hens", fontSize: "1.5vw"},
            {answer: "Calling Birds", fontSize: "1.5vw"},
            {answer: "Gold Rings", fontSize: "1.5vw"},
            {answer: "Geese Laying", fontSize: "1.5vw"},
            {answer: "Swans Swimming", fontSize: "1.5vw"},
            {answer: "Maids Milking", fontSize: "1.5vw"},
            {answer: "Ladies Dancing", fontSize: "1.5vw"},
            {answer: "Lords Leaping", fontSize: "1.5vw"},
        ],
        prompt: 'First 10 unique gifts from the "Twelve days of Christmas"',
    },
    {
        answers: [
            {answer: "Love Actually", fontSize: "1.5vw"},
            {answer: "It's a Wonderful Life", fontSize: "1.4vw"},
            {answer: "Elf", fontSize: "1.5vw"},
            {answer: "The Muppet Christmas Carol", fontSize: "1.4vw"},
            {answer: "Home Alone", fontSize: "1.5vw"},
            {answer: "National Lampoon's Christmas Vacation", fontSize: "1.3vw"},
            {answer: "The Polar Express", fontSize: "1.5vw"},
            {answer: "The Santa Clause", fontSize: "1.5vw"},
            {answer: "Die Hard", fontSize: "1.5vw"},
            {answer: "The Snowman", fontSize: "1.5vw"},
        ],
        prompt: "Britain's Most Popular Christmas Films (as of 2018)",
    },
    {
        answers: [
            {answer: "Flour", fontSize: "1.5vw"},
            {answer: "Butter", fontSize: "1.5vw"},
            {answer: "Sugar / Icing Sugar", fontSize: "1.5vw"},
            {answer: "Eggs", fontSize: "1.5vw"},
            {answer: "Sultanas/Raisins/Apricots", fontSize: "1.5vw"},
            {answer: "Brandy/Sherry/Rum/Cognac", fontSize: "1.5vw"},
            {answer: "Orange/Apple", fontSize: "1.5vw"},
            {answer: "Almonds", fontSize: "1.5vw"},
            {answer: "Mixed Spice", fontSize: "1.5vw"},
            {answer: "Breadcrumbs", fontSize: "1.5vw"},
        ],
        prompt: "The 10 Ingredients in Mary Berry's Christmas Pudding Recipe",
    },
    {
        answers: [
            {answer: "Japan (3,000)", fontSize: "1.5vw"},
            {answer: "Canada (2,100)", fontSize: "1.5vw"},
            {answer: "USA (1,500)", fontSize: "1.5vw"},
            {answer: "Russia (1,000)", fontSize: "1.5vw"},
            {answer: "Norway (900)", fontSize: "1.5vw"},
            {answer: "North Korea (700)", fontSize: "1.5vw"},
            {answer: "China (600)", fontSize: "1.5vw"},
            {answer: "Nepal (500)", fontSize: "1.5vw"},
            {answer: "Denmark/Greenland (500)", fontSize: "1.5vw"},
            {answer: "South Korea (400)", fontSize: "1.5vw"},
        ],
        prompt: "Top 10 Countries by Snowfall since the turn of the 21st Century (as of 2021)",
    },
    {
        answers: [
            {answer: "Snow Scene", fontSize: "1.5vw"},
            {answer: "Robin", fontSize: "1.5vw"},
            {answer: "Reindeer", fontSize: "1.5vw"},
            {answer: "Snowman", fontSize: "1.5vw"},
            {answer: "Father Christmas", fontSize: "1.5vw"},
            {answer: "Snowflakes", fontSize: "1.5vw"},
            {answer: "Nativity", fontSize: "1.5vw"},
            {answer: "Holly", fontSize: "1.5vw"},
            {answer: "Decorations", fontSize: "1.5vw"},
            {answer: "Angels", fontSize: "1.5vw"},
        ],
        prompt: "Top 10 Christmas Card Images (2018)",
    },
    {
        answers: [
            {answer: "There's", fontSize: "1.5vw"},
            {answer: "Afraid", fontSize: "1.5vw"},
            {answer: "Banish", fontSize: "1.5vw"},
            {answer: "Plenty", fontSize: "1.5vw"},
            {answer: "Spread", fontSize: "1.5vw"},
            {answer: "Around", fontSize: "1.5vw"},
            {answer: "Prayer", fontSize: "1.5vw"},
            {answer: "Having", fontSize: "1.5vw"},
            {answer: "Outside", fontSize: "1.5vw"},
            {answer: "Window", fontSize: "1.5vw"},
        ],
        prompt: "First 10 words of 6 letters or more from the song 'Do They Know It's Christmas'",
    },
]

export default rounds;