const rounds = [
    {
        answers: [
            {answer: "BANGLE", fontSize: "1.5vw"},
            {answer: "BEAGLE", fontSize: "1.5vw"},
            {answer: "BOGGLE", fontSize: "1.5vw"},
            {answer: "BUNGLE", fontSize: "1.5vw"},
            {answer: "BURGLE", fontSize: "1.5vw"},
            {answer: "DANGLE", fontSize: "1.5vw"},
            {answer: "DINGLE", fontSize: "1.5vw"},
            {answer: "GAGGLE", fontSize: "1.5vw"},
            {answer: "GARGLE", fontSize: "1.5vw"},
            {answer: "GIGGLE", fontSize: "1.5vw"},
        ],
        prompt: 'The first 10 six-letter words ending in the letters "GLE"',
    },
    {
        answers: [
            {answer: "Alaska", fontSize: "1.5vw"},
            {answer: "Arizona", fontSize: "1.5vw"},
            {answer: "California", fontSize: "1.5vw"},
            {answer: "Hawaii", fontSize: "1.5vw"},
            {answer: "Idaho", fontSize: "1.5vw"},
            {answer: "Montana", fontSize: "1.5vw"},
            {answer: "Nevada", fontSize: "1.5vw"},
            {answer: "Oregon", fontSize: "1.5vw"},
            {answer: "Utah", fontSize: "1.5vw"},
            {answer: "Washington", fontSize: "1.5vw"},
        ],
        prompt: 'The 10 most westerly US states',
    },
    {
        answers: [
            {answer: "Carry on Sergeant", fontSize: "1.4vw"},
            {answer: "Carry on Nurse", fontSize: "1.5vw"},
            {answer: "Carry on Teacher", fontSize: "1.5vw"},
            {answer: "Carry on Constable", fontSize: "1.5vw"},
            {answer: "Carry on Cabby", fontSize: "1.5vw"},
            {answer: "Carry on Spying", fontSize: "1.5vw"},
            {answer: "Carry on Cowboy", fontSize: "1.5vw"},
            {answer: "Carry on Doctor", fontSize: "1.5vw"},
            {answer: "Carry on Again Doctor", fontSize: "1.5vw"},
            {answer: "Carry on Matron", fontSize: "1.5vw"},
        ],
        prompt: 'The 10 "Carry On …" films with jobs in the title',
    },
    // {
    //     answers: [
    //         {answer: "Lead (Pb)", fontSize: "1.5vw"},
    //         {answer: "Neptunium (Np)", fontSize: "1.5vw"},
    //         {answer: "Palladium (Pd)", fontSize: "1.5vw"},
    //         {answer: "Platinum (Pt)", fontSize: "1.5vw"},
    //         {answer: "Phosphorus (P)", fontSize: "1.5vw"},
    //         {answer: "Plutonium (Pu)", fontSize: "1.5vw"},
    //         {answer: "Polonium (Po)", fontSize: "1.5vw"},
    //         {answer: "Praseodymium (Pr)", fontSize: "1.5vw"},
    //         {answer: "Promethium (Pm)", fontSize: "1.5vw"},
    //         {answer: "Proactinum (Pa)", fontSize: "1.5vw"},
    //     ],
    //     prompt: 'The 10 elements with the letter "P" in their chemical symbol',
    // },
    {
        answers: [
            {answer: "Paris (11.017M)", fontSize: "1.5vw"},
            {answer: "London (9.304M)", fontSize: "1.5vw"},
            {answer: "Madrid (6.618M)", fontSize: "1.5vw"},
            {answer: "Rome (4.257M)", fontSize: "1.5vw"},
            {answer: "Berlin (3.562M)", fontSize: "1.5vw"},
            {answer: "Athens (3.153M)", fontSize: "1.5vw"},
            {answer: "Lisbon (2.957M)", fontSize: "1.5vw"},
            {answer: "Brussels (2.081M)", fontSize: "1.5vw"},
            {answer: "Vienna (1.903M)", fontSize: "1.5vw"},
            {answer: "Bucharest (1.83M)", fontSize: "1.5vw"},
        ],
        prompt: 'The 10 most populous capital cities in the EU',
    },
    {
        answers: [
            {answer: "Cinderella (1950)", fontSize: "1.4vw"},
            {answer: "Alice in Wonderland (1951)", fontSize: "1vw"},
            {answer: "Peter Pan (1953)", fontSize: "1.5vw"},
            {answer: "Lady and the Tramp (1955)", fontSize: "1.5vw"},
            {answer: "Sleeping Beauty (1959)", fontSize: "1.5vw"},
            {answer: "101 Dalmations (1961)", fontSize: "1.5vw"},
            {answer: "The Sword in the Stone (1963)", fontSize: "1.5vw"},
            {answer: "The Jungle Book (1967)", fontSize: "1.5vw"},
            {answer: "The Aristocats (1970)", fontSize: "1.5vw"},
            {answer: "Robin Hood (1973)", fontSize: "1.5vw"},
        ],
        prompt: "The first 10 animated Disney feature films released from 1950",
    },
]

export default rounds;